name: CI tests

on: push

jobs:
  build:
    name: CI job
    runs-on: ubuntu-latest
    steps:
    - name: Prepare environment
      env:
        MY_VAR: Hi there!
      run: |
        echo $MY_VAR.
